// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/database/database.go
//
// Generated by this command:
//
//	mockgen -source=./internal/database/database.go -destination=./internal/database/mock_database.go -package=database
//

// Package database is a generated GoMock package.
package database

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// SaveTrade mocks base method.
func (m *MockDatabase) SaveTrade(data map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTrade", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTrade indicates an expected call of SaveTrade.
func (mr *MockDatabaseMockRecorder) SaveTrade(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTrade", reflect.TypeOf((*MockDatabase)(nil).SaveTrade), data)
}
