version: '3.8'

services:
  tickflow:
    build: .
    container_name: TickFlow
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app_network
    environment:
      MONGO_URI: "mongodb://localhost:27017"
    command: >
      sh -c "sed -i 's|mongodb://localhost:27017|mongodb://admin:adminpassword@db:27017/rates?authSource=admin|' .config/local.yaml && ./TickFlow"

  db:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rates
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    networks:
      - app_network
    volumes:
      - db_data:/data/db
      - ./scripts/init.js:/docker-entrypoint-initdb.d/init.js
    healthcheck:
      test: [ "CMD-SHELL", "echo 'db.runCommand({ping:1}).ok' | mongosh --quiet \
          --host localhost --port 27017 \
          -u admin -p adminpassword \
          --authenticationDatabase admin \
          | grep 1" ]
      interval: 10s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - app_network
    volumes:
      - ./.config/prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  app_network:

volumes:
  db_data:
