version: '3.8'

services:
  tickflow:
    build: .
    container_name: tickflow
    ports:
      - "8080:8080"
    networks:
      - app_network
    command: "./TickFlow"
    environment:
      MONGO_URI: "mongodb://root:password@mongodb_stream:27017/?replicaSet=rs0&authSource=admin"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_tickflow
    ports:
      - "9091:9090"
    networks:
      - app_network
    volumes:
      - ./.config/prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  app_network:
    driver: bridge
